Resources:
  FractalLambdaS3FileManagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: FractalLambdaS3FileManagerPolicy
      Description: Allow Lambda to list and upload files to S3
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - arn:aws:s3:::${self:custom.config.${self:custom.stage}.bucket_name}
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::${self:custom.config.${self:custom.stage}.bucket_name}/*
