Resources:
  LambdaS3ExtractionGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaS3ExtractionGatewayRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: LambdaS3ExtractionGatewayPolicy
