Resources:
  LambdaNotificationOverclockingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: LambdaNotificationOverclockingPolicy
      Description: Allow Lambda to read S3 files and send emails via SES
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - arn:aws:s3:::${self:custom.config.${self:custom.stage}.bucket_name}
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - arn:aws:s3:::${self:custom.config.${self:custom.stage}.bucket_name}/*
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"
